[package]
name = "fuse_terminated"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"
